django_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('question/', include('question.urls')),  #add the proper path pattern
    path('admin/',admin.site.urls),
    path('', include('question.urls')),

]

question/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 31 12:01:10 2021

@author: Vashti
"""
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'question'

#sets the path for the view
urlpatterns = [
    path('',views.IndexView.as_view() , name='index'),
    path('<int:pk>/', views.DetailView.as_view() , name='detail'), # ex: /question/5/    
    path('<int:pk>/results/' ,views.ResultsView.as_view() ,name='results'), # ex: /question/5/results/   
    path('<int:question_id>/vote/', views.vote,name='vote'),     # ex: /question/5/vote/
    path('signup_view/', views.signup_view, name="signup_view"),
    path( 'login/', auth_views.LoginView.as_view(template_name='question/login.html'), name='login'),
    path( 'logout/', auth_views.LogoutView.as_view(template_name='question/logout.html'), name='logout'),
    path('question_create', views.QuestionCreate.as_view(template_name='question/create_question.html'), name='question_create' ),
    path('<int:pk>/delete', views.QuestionDeleteView.as_view(template_name='question/confirm_delete.html'), name='delete' ),
    path('<int:pk>/update', views.QuestionUpdate.as_view(), name='update' ),

    ]

question/models.py
from django.db import models

from django.utils import timezone
import datetime
# Create your models here.

def user_directory_path(instance, filename):
    #file will be uploaded to items_images/user_<id>/<filename>
    return 'items_images/user_{0}/{1}'.format(instance.id, filename)


class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')
    #image = models.ImageField(upload_to = user_directory_path)
    question_id = models.IntegerField(default=0)
    def __str__(self):
            return self.question_text
    def was_published_recently(self):
        now = timezone.now() 
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
    def isAvalidQuestion(self):
        return self.question.question_id < 0
    
class User(models.Model):
    choice =   models.ForeignKey(Choice, on_delete=models.CASCADE)
    user_name =  models.CharField(max_length=200)
    def __str__(self):
        return self.user_name

question/forms.py
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 28 11:46:20 2021

@author: Vashti
"""

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
        
class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

question/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Question
from django.http import Http404

from django.http import HttpResponseRedirect
from .models import Choice
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView


from django.views import generic

from django.utils import timezone

class QuestionUpdate(UpdateView):
    model = Question
    fields = ['question_text', 'pub_date', 'image']
    template_name = 'question/update_question.html'
    success_url ="/"


class QuestionCreate(CreateView):
  
    # specify the model for create view
    model = Question
  
    # specify the fields to be displayed
  
    fields = ['question_text', 'pub_date', 'image']
    
    success_url ="/"

class QuestionDeleteView(DeleteView):
    # specify the model you want to use
    model = Question
      
    # can specify success url
    # url to redirect after successfully
    # deleting object
    success_url ="/"


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name= 'question/index.html'
    context_object_name= 'latest_question_list'
    # def get_queryset(self):
    #     #Return the last five published questions.
    #     return Question.objects.order_by('-pub_date')[:5]
    def get_queryset(self):
        #Excludes any questions that aren't published yet.
        return Question.objects.filter(pub_date__lte=timezone.now())

class DetailView(generic.DetailView):
    model = Question
    template_name= 'question/detail.html'
    
    
class ResultsView(generic.DetailView):
    model = Question
    template_name= 'question/results.html'



def index(request):
    '''
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)
    #return HttpResponse("Hello, world. You're at the polls???(should be question tho) index.")
    '''
    latest_question_list = Question.objects.order_by('-pub_date')[:2]
    #output = ', '.join([q.question_text for q in latest_question_list])
    #return HttpResponse(output)
    template = loader.get_template('question/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))



def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
        
    return render(request,'question/detail.html',{'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'question/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice= question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'question/detail.html', 
                      {'question': question,'error_message': "You didn't select a choice.",})
    else:
        selected_choice.votes+= 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('question:results', args=(question.id,)))


from .forms import SignUpForm
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect

def signup_view(request):
    form = SignUpForm(request.POST)
    print( 'form', form )
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('question:index')
    return render(request, 'question/signup.html', {'form': form})

question/templates/question/confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

question/templates/question/create_question.html
<form method="POST" enctype="multipart/form-data">
  
    <!-- Security token -->
    {% csrf_token %}
  
    <!-- Using the formset -->
    {{ form.as_p }}
      
    <input type="submit" value="Submit">
</form>

question/templates/question/detail.html
{% load static %}
<h1>{{question.question_text }}</h1>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<img src="{% static question.image.url %}" width=100>
<form action="{% url 'question:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter }}" value="{{ choice.id }}">
	<label for="choice{{forloop.counter }}">{{ choice.choice_text }}</br>
	{% endfor %}
	<input type="submit" value="Vote">
</form>

question/templates/question/index.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'question/style.css' %}">
</head>

{% if latest_question_list%}
<ul>
	{% for question in latest_question_list%}
	<li><a href="{% url 'question:detail' question.id %}">{{question.question_text}}</a></li>
	{% endfor%}
</ul>
{% else %}
	<p>No question are available.</p>
{% endif%}

question/templates/question/login.html
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

<p>No account?  <a href = "{% url 'question:signup_view' %}"  >register</a></p>

question/templates/question/logout.html
<h1>Logged out</h1>
<p> Login again? <a href="{% url 'question:login' %}">go here</a></p>
<p> no account? <a href="{% url 'question:signup_view' %}">register</a>

question/templates/question/results.html
<h1>{{ question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all%}
        <li>{{ choice.choice_text}} --{{ choice.votes}} vote{{ choice.votes|pluralize}}</li>
    {% endfor%}
</ul>
<a href="{% url 'question:detail' question.id %}">Vote again?</a>

question/templates/question/signup.html
<h2>Sign up Form</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>

question/templates/question/update_question.html
<form method="POST" enctype="multipart/form-data">
  
    <!-- Security token -->
    {% csrf_token %}
  
    <!-- Using the formset -->
    {{ form.as_p }}
      
    <input type="submit" value="Submit">
</form>